# Generated by Django 2.0.3 on 2018-08-19 15:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
                ('resultado', models.BooleanField(default=False, verbose_name='resultado')),
                ('votoSim', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='votosim')),
                ('votoNao', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='votonao')),
                ('final_time', models.TimeField(default=datetime.datetime(2018, 8, 19, 13, 25, 38, 8414), verbose_name='horario de final')),
                ('active', models.BooleanField(default=True, verbose_name='ativado')),
            ],
            options={
                'verbose_name': 'votação',
                'verbose_name_plural': 'votações',
            },
        ),
        migrations.CreateModel(
            name='Votadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='id-user')),
                ('leiId', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='id-lei')),
            ],
            options={
                'verbose_name': 'votado',
                'verbose_name_plural': 'votadas',
            },
        ),
    ]
