# Generated by Django 2.0.3 on 2018-08-19 18:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacaoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('leiId', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='id-lei')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.AlterField(
            model_name='votacao',
            name='final_time',
            field=models.TimeField(default=datetime.datetime(2018, 8, 19, 16, 22, 26, 801629), verbose_name='horario de final'),
        ),
    ]
